/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Conexion.Controlador.CRUDCliente;
import Controlador.Conexion.Controlador.CrudProveedor;
import Modelo.POJOClientes;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author waska
 */
public class clientes2 extends javax.swing.JFrame {

    /**
     * Creates new form prueba
     */
    int datoSeleccionado =  -1;
    public clientes2() {
       
        initComponents();
 setExtendedState(MAXIMIZED_BOTH);
 rsscalelabel.RSScaleLabel.setScaleLabel(fondo, "src/vista.imagenes/background formulario.png");
 mostrar();
 

    }
public void mostrar(){
    try {
        DefaultTableModel modelo;
        CRUDCliente cli = new CRUDCliente();
        modelo = cli.mostrarDatos();
        Tablaclientes.setModel(modelo);
        
        
    }catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        
    }
}
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cedula = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        Numero = new javax.swing.JFormattedTextField();
        btneliminar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btneditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablaclientes = new javax.swing.JTable();
        btncerrar1 = new javax.swing.JButton();
        apellido = new javax.swing.JFormattedTextField();
        nombre = new javax.swing.JFormattedTextField();
        correo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextDireccion = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(390, 200));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Cedula");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel4.setText("Numero");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jLabel2.setText("Nombre del Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        try {
            cedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cedula.setText("~cedula");
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 350, -1));

        jLabel6.setText("Apellido Del Clientre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        try {
            Numero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 350, -1));

        btneliminar.setForeground(new java.awt.Color(255, 0, 0));
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 100, 40));

        btnactualizar.setForeground(new java.awt.Color(0, 51, 255));
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 100, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Editar Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 360, -1));

        btneditar.setForeground(new java.awt.Color(0, 255, 51));
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        getContentPane().add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 100, 40));

        Tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, ""},
                {null, null, null, ""},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tablaclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablaclientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 560, 120));

        btncerrar1.setForeground(new java.awt.Color(0, 0, 0));
        btncerrar1.setText("Regresar");
        btncerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btncerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 100, 40));

        try {
            apellido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });
        apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoKeyTyped(evt);
            }
        });
        getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 350, 30));

        try {
            nombre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 350, 30));
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 350, -1));

        jLabel7.setText("Correo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarKeyTyped(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 350, -1));

        jLabel5.setText("Direccion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jTextDireccion.setColumns(20);
        jTextDireccion.setRows(5);
        jScrollPane2.setViewportView(jTextDireccion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 350, 40));

        fondo.setAutoscrolls(true);
        fondo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -70, 1590, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
    int datoSeleccionado = Tablaclientes.getSelectedRow();
    if (datoSeleccionado >= 0) {
        String idCliente = String.valueOf(Tablaclientes.getValueAt(datoSeleccionado, 0));
        CRUDCliente cli = new CRUDCliente();
        if (JOptionPane.showConfirmDialog(rootPane,
                "Se eliminará el registro, ¿desea continuar?",
                "Eliminar Registro",
                JOptionPane.WARNING_MESSAGE,
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            cli.eliminar(idCliente);
            mostrar();
            JOptionPane.showMessageDialog(null, "Dato eliminado correctamente");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Debe seleccionar un registro de la tabla");
    }
       // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btncerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrar1ActionPerformed
   this.dispose();  
               // TODO add your handling code here:
    }//GEN-LAST:event_btncerrar1ActionPerformed

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed


    
   // TODO add your handling code here:
    }//GEN-LAST:event_apellidoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed

      // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
                && car != 'á'//minusculas
                && car != 'é'
                && car != 'í'
                && car != 'ó'
                && car != 'ú'
                && car != 'Á' //Mayusculas
                && car != 'Ë'
                && car != 'Í'
                && car != 'Ó'
                && car != 'Ú'
                && car != 'Ñ'
                && car != 'ñ'
                && car != 'Ü'
                && car != 'ü'
                && (car != (char) KeyEvent.VK_SPACE)){
        
        evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_nombreKeyTyped

    private void apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoKeyTyped
char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
                && car != 'á'//minusculas
                && car != 'é'
                && car != 'í'
                && car != 'ó'
                && car != 'ú'
                && car != 'Á' //Mayusculas
                && car != 'Ë'
                && car != 'Í'
                && car != 'Ó'
                && car != 'Ú'
                && car != 'Ñ'
                && car != 'ñ'
                && car != 'Ü'
                && car != 'ü'
                && (car != (char) KeyEvent.VK_SPACE)){
        
        evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoKeyTyped

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
try {
        DefaultTableModel modelo;
        CrudProveedor cli = new CrudProveedor();

        if (buscar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escriba el dato a buscar");
            mostrar();
        } else {
            modelo = cli.buscarDatos(buscar.getText());
            Tablaclientes.setModel(modelo);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        mostrar();
    }          // TODO add your handling code here:
 try {
DefaultTableModel modelo;
CRUDCliente cli = new CRUDCliente();
modelo = cli.buscarDatos(buscar.getText());
if (buscar.getText().equals("")){
     JOptionPane.showMessageDialog(null, "Escriba el dato a buscar");
mostrar();

} else {
Tablaclientes.setModel(modelo);
}
} catch (Exception e) {
JOptionPane.showMessageDialog(null, e);
}

    }//GEN-LAST:event_buscarActionPerformed

    private void TablaclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaclientesMouseClicked
if (datoSeleccionado >= 0) {
String dato =
String.valueOf(Tablaclientes.getValueAt(datoSeleccionado, 0));
CRUDCliente cli = new CRUDCliente();
if (JOptionPane.showConfirmDialog(rootPane,
"Se eliminará el registro, ¿desea continuar?",

"Eliminar Registro",
JOptionPane.WARNING_MESSAGE,
JOptionPane.YES_NO_OPTION)
== JOptionPane.YES_OPTION) {

cli.eliminar(dato);
mostrar();
JOptionPane.showMessageDialog(null,
"Dato eliminado correctamente");
}

}        // TODO add your handling code here:
    }//GEN-LAST:event_TablaclientesMouseClicked

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
    int datoSeleccionado = Tablaclientes.getSelectedRow();
    if (datoSeleccionado >= 0) {
        String idCliente = String.valueOf(Tablaclientes.getValueAt(datoSeleccionado, 0));
        String nombre = String.valueOf(Tablaclientes.getValueAt(datoSeleccionado, 1));
        String apellido = String.valueOf(Tablaclientes.getValueAt(datoSeleccionado, 2));
        String correo = String.valueOf(Tablaclientes.getValueAt(datoSeleccionado, 3));
         String telefono = String.valueOf(Tablaclientes.getValueAt(datoSeleccionado, 4));
        String direccion = String.valueOf(Tablaclientes.getValueAt(datoSeleccionado, 5));

        
        this.nombre.setText(nombre);
        this.apellido.setText(apellido);
        this.correo.setText(correo);
        this.jTextDireccion.setText(direccion);
        this.Numero.setText(telefono);
        this.cedula.setText(idCliente);
        
        
        
    } else {
        JOptionPane.showMessageDialog(null, "Debe seleccionar un registro de la tabla");
    
}        // TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
try {
    // Obtener los datos ingresados por el usuario
    String ced = cedula.getText();
    String nom = nombre.getText();
    String ape = apellido.getText();
    String cor = correo.getText();
    String num = Numero.getText();
    String dir = jTextDireccion.getText();

  
    // Verificar si hay campos vacíos
    if (ced.isEmpty() || nom.isEmpty() || ape.isEmpty() || dir.isEmpty() || num.isEmpty() || cor.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
    } else {
        POJOClientes cliente = new POJOClientes(ced, nom, ape, cor, num, dir);

        // Crear una instancia de la clase CRUDCliente
        CRUDCliente crudCliente = new CRUDCliente();
        crudCliente.actualizarCliente(cliente);

        mostrar();
limpiarCampos();
        JOptionPane.showMessageDialog(null, "Cliente actualizado exitosamente");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}
            // TODO add your handling code here:
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyTyped
        // TODO add your handling code here:
        try {
        DefaultTableModel modelo;
        CRUDCliente cli = new CRUDCliente();
        if (buscar.getText().equals("")) {
            mostrar();
        } else {
            modelo = cli.buscarDatos(buscar.getText());
            Tablaclientes.setModel(modelo);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);       
              }
    }//GEN-LAST:event_buscarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientes2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Numero;
    private javax.swing.JTable Tablaclientes;
    private javax.swing.JFormattedTextField apellido;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btncerrar1;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JTextField buscar;
    private javax.swing.JFormattedTextField cedula;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextDireccion;
    private javax.swing.JFormattedTextField nombre;
    // End of variables declaration//GEN-END:variables


private void limpiarCampos() {
    nombre.setText("");
    apellido.setText("");
    correo.setText("");
    Numero.setText("");
    cedula.setText("");
    jTextDireccion.setText("");
}


}
