/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Conexion.Controlador.CRUDProducto;
import Controlador.Conexion.Controlador.CrudProveedor;
import Modelo.POJOProducto;
import java.awt.List;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.PROPERTIES;
import javax.swing.JOptionPane;
import Modelo.POJOCategoria;
import Modelo.POJOMarca;
import java.util.ArrayList;
import Modelo.POJOProveedor;
import java.math.BigDecimal;


/**
 *
 * @author waska
 */
public class productos1 extends javax.swing.JFrame {

    int datoSeleccionado = -1;
    int Producto;    
    
    
    /**
     * Creates new form prueba
     */
    public productos1() {
     initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        rsscalelabel.RSScaleLabel.setScaleLabel(fondo, "src/vista.imagenes/background formulario.png");
}
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextPV = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        btncerrar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        TextPC = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        textcant = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        alcohol = new javax.swing.JFormattedTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(390, 200));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Precio de Compra");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jLabel2.setText("Nombre del Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        TextPV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TextPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPVActionPerformed(evt);
            }
        });
        getContentPane().add(TextPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 350, -1));

        jLabel6.setText("Descripcion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        btncerrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btncerrar.setForeground(new java.awt.Color(255, 0, 0));
        btncerrar.setText("Regresar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 130, 70));

        btnguardar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(51, 255, 51));
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 130, 70));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Agregar Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 360, -1));

        try {
            Nombre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("******************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 350, 30));

        jLabel5.setText("Precio de venta");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        TextPC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TextPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPCActionPerformed(evt);
            }
        });
        getContentPane().add(TextPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 350, -1));

        jLabel7.setText("Cantidad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, -1));

        textcant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        getContentPane().add(textcant, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 100, -1));

        Descripcion.setColumns(20);
        Descripcion.setRows(5);
        jScrollPane1.setViewportView(Descripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 350, 50));

        jLabel8.setText("% de Alchohol");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        alcohol.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        alcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alcoholActionPerformed(evt);
            }
        });
        getContentPane().add(alcohol, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 40, -1));

        fondo.setAutoscrolls(true);
        fondo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1590, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void TextPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPVActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_btncerrarActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void TextPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPCActionPerformed

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
                && car != 'á'//minusculas
                && car != 'é'
                && car != 'í'
                && car != 'ó'
                && car != 'ú'
                && car != 'Á' //Mayusculas
                && car != 'Ë'
                && car != 'Í'
                && car != 'Ó'
                && car != 'Ú'
                && car != 'Ñ'
                && car != 'ñ'
                && car != 'Ü'
                && car != 'ü'
                && (car != (char) KeyEvent.VK_SPACE)){
        
        evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_NombreKeyTyped

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

 String nombre = Nombre.getText();
    String descripcion = Descripcion.getText();
    String precioCompra = TextPC.getText();
    String precioVenta = TextPV.getText();
    String porcentajeAlcohol = alcohol.getText();
    String cantidad = textcant.getText();

    // Crear un objeto del producto con los datos ingresados
    POJOProducto producto = new POJOProducto(0, nombre, descripcion, precioCompra, precioVenta, porcentajeAlcohol, cantidad);

    // Crear una instancia del CRUDProducto
    CRUDProducto crudProducto = new CRUDProducto();

    // Llamar al método Guardar del CRUDProducto para guardar el producto en la base de datos
    crudProducto.Guardar(producto);
    
    // Limpiar los campos del formulario
     limpiarCampos();

    // Mostrar un mensaje de éxito
    JOptionPane.showMessageDialog(null, "Producto guardado correctamente");

        
                       
    }//GEN-LAST:event_btnguardarActionPerformed

    private void alcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alcoholActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alcoholActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productos1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea Descripcion;
    public javax.swing.JFormattedTextField Nombre;
    public javax.swing.JFormattedTextField TextPC;
    private javax.swing.JFormattedTextField TextPV;
    public javax.swing.JFormattedTextField alcohol;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField textcant;
    // End of variables declaration//GEN-END:variables

private void limpiarCampos() {
    Nombre.setText("");
    Descripcion.setText("");
    TextPC.setText("");
    TextPV.setText("");
    textcant.setText("");
    alcohol.setText("");
}
}